spring.kafka.bootstrap-servers: localhost:9092

spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.enable-auto-commit: false
spring.kafka.consumer.auto-offset-reset: earliest
spring:
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages:: com.epam.kafka.training


kafka:
  bootstrapServer: localhost:9092
  trackerConsumerGroupId: tracker
  loggingConsumerGroupId: logging
  inputTopic: taxi_input_topic
  outputTopic: taxi_output_topic
  DQLPostfix: .failure



